/* Please Note. All words are in lowercase  */
class partsOfSpeech {
  static List<String> articles = ["a", "an", "the"];
  static List<String> conjunctions = [
    "and",
    "but",
    "for",
    "nor",
    "or",
    "so",
    "yet"
  ];
  static List<String> personalizedPartsforFilteringStart = [
    "when",
    "if",
    'after',
    "before",
    'amid',
    'too',
    'for',
  ];
  static List<String> personalizedPartsforFilteringEnd = [];
  static List<String> unwantedText = ["-", "...", '|', '.', ',', 'is', 'are'];
  static List<String> auxiliaryVerbs = [
    "am",
    "is",
    "are",
    "was",
    "were",
    "being",
    "been",
    "will",
    "be",
    "has",
    "have",
    "had",
    "having",
    "will",
    "have"
        "does",
    "do",
    "did",
    "will" "do"
  ];
  
  static List<String> prepositions = [
    "with",
    "in",
    "from",
    "about",
    "after",
    "ago",
    "around",
    "at",
    "before",
    "by",
    "circa",
    "during",
    "following",
    "for",
    "gone",
    "on",
    "past",
    "prior to",
    "since",
    "until",
    "till",
    "up to",
    "up until",
    "aboard",
    "above",
    "across",
    "against",
    "alongside",
    "amid",
    "among",
    "apart from",
    "astride",
    "at",
    "atop",
    "behind",
    "below",
    "beneath",
    "beside",
    "between",
    "beyond",
    "by",
    "close to",
    "far",
    "far from",
    "forward of",
    "from",
    "in",
    "in between",
    "in front of",
    "inside",
    "into",
    "minus",
    "near",
    "near to",
    "next to",
    "of",
    "off",
    "on",
    "on board",
    "on top of",
    "onto",
    "upon",
    "opposite",
    "out",
    "out of",
    "outside",
    "outside of",
    "over",
    "round",
    "through",
    "throughout",
    "to",
    "together with",
    "toward/towards",
    "whether",
    "under",
    "underneath",
    "up against",
    "with",
    "within",
    "without",
    "above",
    "across",
    "against",
    "ahead",
    "along",
    "along with",
    "amid",
    "around",
    "away",
    "away from",
    "behind",
    "below",
    "beneath",
    "by means of",
    "down",
    "further to",
    "in between",
    "into",
    "off",
    "off of",
    "on",
    "onto",
    "over",
    "out of",
    "past",
    "round",
    "through",
    "toward",
    "towards",
    "under",
    "up",
    "via",
    "about",
    "according to",
    "anti",
    "as",
    "as for",
    "as per",
    "as to",
    "as well as",
    "aside from",
    "bar",
    "barring",
    "because of",
    "besides",
    "but for",
    "by",
    "but",
    "concerning",
    "considering",
    "contrary to",
    "counting",
    "cum",
    "depending on",
    "despite",
    "due to",
    "except",
    "except for",
    "excepting",
    "excluding",
    "given",
    "in addition to",
    "in case of",
    "in face of",
    "in favor of",
    "in favour of",
    "in light of",
    "in spite of",
    "in view of",
    "including",
    "instead of",
    "less",
    "like",
    "notwithstanding",
    "of",
    "on account of",
    "on behalf of",
    "other than",
    "owing to",
    "pending",
    "per",
    "plus",
    "preparatory to",
    "pro",
    "re",
    "regarding",
    "regardless of",
    "save",
    "save for",
    "saving",
    "than",
    "thanks to",
    "unlike",
    "versus",
    "with reference to",
    "with regard to",
    "worth"
  ];
  static List<String> unwantedTextForFiltering = [
    "youtube",
    '| ',
    '...',
    'techsupport',
    'ways',
    'top',
    'reasons',
    'fixes',
    'tips',
    'common',
    '-',
    'steps',
    'amazon',
  ]; /* ... weeds out the incomplete sentences */
  static List<String> allavailablePartsofSpeech = articles +
      conjunctions +
      personalizedPartsforFilteringStart +
      personalizedPartsforFilteringEnd +
      prepositions +
      auxiliaryVerbs +
      unwantedText;
  static List<String> partsOfSpeechforAcceptedResultFiltering =
      personalizedPartsforFilteringStart; //+
          // prepositions +
          // personalizedPartsforFilteringEnd;
}
